##**넘파이**

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
print(arr1)

arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(arr1.shape, arr1.ndim) # shape 하면 튜플로 반환함.
print(arr2.shape, arr2.ndim) # ndim은 몇차원 배열인지

(4,) 1
(2, 4) 2


In [ ]:
arr = np.array([1, 2, 3])
print(type(arr))
print(arr.dtype)

arr = np.array([1, 2, 3.3])
#리스트 내에 데이터 타입이 섞여 있으면 강제 형 변환 발생
print(type(arr))
print(arr.dtype)


<class 'numpy.ndarray'>
int64
<class 'numpy.ndarray'>
float64


In [ ]:
arr = np.arange(5) #숫자 n이 하나면 0~n-1 까지
print(arr)

arr = np.arange(5, 10) # 숫자 n 이 두개면 첫번째 n ~ 두번째 n-1 까지
print(arr)


[0 1 2 3 4]
[5 6 7 8 9]


In [ ]:
arr = np.linspace(1, 10, 20) # 1부터 10까지 20개 값으로 생성
print(arr)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [ ]:
arr = np.zeros(5) # 숫자 n개의 개수만큼 0으로 채운 배열 생성
print(arr, arr.shape)

arr = np.zeros([2 , 3]) # 2행 3열 0으로 채운 배열 생성
print(arr, arr.shape)

[0. 0. 0. 0. 0.] (5,)
[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)


In [ ]:
arr = np.full(3, 8) # 안에 들어가는 인자는 ( shape, 연속할 값 )
print(arr, arr.shape)

arr = np.full([2, 2], 7) # 2행 2열을 7로 채우는 2차원 배열 생성
print(arr, arr.shape)

[8 8 8] (3,)
[[7 7]
 [7 7]] (2, 2)


In [ ]:
arr = np.array([1, 2, 3])

arr_z = np.zeros_like(arr) # 기존 배열의 shape과 동일한 형태에서 0으로 채움.
print(arr_z)

arr_o = np.ones_like(arr) # 기존 배열의 shape과 동일한 형태에서 1로 채움.
print(arr_o)

[0 0 0]
[1 1 1]


In [ ]:
arr = np.arange(6)
print(arr)

arr = arr.reshape(2, 3) # 기존 배열을 (행, 열) 형태 배열로 변환
print(arr)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [ ]:
li = [1, 2, 3]
ar = np.array([1, 2, 3])

print(li[1])
print(ar[1])
#인덱스 값은 항상 0으로 시작함.

2
2


In [ ]:
arr1d = np.arange(1, 20, 2) # 1부터 19까지 2간격으로 배열생성
arr2d = arr1d.reshape(2, 5) # 2행 5열로 변환

print(arr2d)
print(arr2d[0,2]) # arr2d의 0행 2열 번째 요소 인덱싱

[[ 1  3  5  7  9]
 [11 13 15 17 19]]
5


In [ ]:
arr1d = np.arange(1, 21)
arr2d = arr1d.reshape(4, 5) # 4행 5열 배열 변환

print(arr2d)
print()
print(arr2d[0:3, 0:4]) # 0행부터 2행까지, 0열부터 3열까지 슬라이싱 인덱싱

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]]


In [ ]:
arr1d = np.arange(1, 10)
arr2d = arr1d.reshape(3, 3)

print(arr2d)
print()
print(arr2d[[0, 2], 1])
print()
print(arr2d[[0, 1], 2])
print()
print(arr2d[[0, 1], 0:2])
print()
print(arr2d[[0, 1]])

# 팬시 인덱싱, ( 0행 또는 2행의 ) 1열 요소 인덱싱

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[2 8]

[3 6]

[[1 2]
 [4 5]]

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.arange(1, 13)
print(arr)

farr = np.full(12, False) # shape 만큼 False, 아무것도 반환 x
print(arr[farr])

print(arr[arr > 5]) # 조건식 인덱싱, 5 초과하는 요소 반환

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[]
[ 6  7  8  9 10 11 12]


In [ ]:
arr = np.array([4, 3, 5, 2, 1])
print('원본 :', arr)



sortArr = np.sort(arr) # '함수', 원 배열은 유지한 채 정렬 결과 반환
print('정렬 :', sortArr)

#np.sort(arr)[::-1]  > 내림차순


indexArr = np.argsort(arr)
print("argsort :", indexArr)



arr.sort() # '메소드', 원 배열 자체를 정렬
print('정렬 :', arr)

indexArr = np.argsort(arr)
print("argsort :", indexArr)

원본 : [4 3 5 2 1]
정렬 : [1 2 3 4 5]
argsort : [4 3 1 0 2]
정렬 : [1 2 3 4 5]
argsort : [0 1 2 3 4]


In [ ]:
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

#axis = 0  행
#axis = 1  열

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


##**판다스**

In [ ]:
import pandas as pd

"""
시리즈: 데이터 유형을 저장할 수 있는 1차원 열 형태의 자료구조.
데이터프레임: 행과 열로 구성된 자료구조, 시리즈가 합쳐진 형태라 봐도 무방
"""
"""
@데이터 프레임 확인(조회)
df.values : 데이터프레임에 포함된 값을 별도로 제공하는 속성
df.columns : 데이터프레임의 열 이름을 별도로 제공하는 속성
df.count(): 데이터프레임의 행 개수를 제공하는 속성
df.info(): 데이터프레임에 대한 기본 정보를 제공하는 함수
df.value_counts():데이터프레임에 포함된 값의 발생 횟수를 제공하는 함수
df.head(): 데이터프레임 앞 일부 데이터를 제공하는 함수
df.tail() : 데이터프레임 뒤 일부 데이터를 제공하는 함수
"""

# 딕셔너리 형태 데이터 프레임
data = {
    'fruit':['apple', 'banana', 'carrot'],
    'animal' : ['alpaca', 'bee', 'chicken']
}
df = pd.DataFrame(data)
print(df)

print()


# 리스트 형태 데이터 프레임
data = [
    ['apple', 'banana', 'carrot'],
    ['alpaca', 'bee', 'chicken']
]

data = [
    ['apple', 'alpaca'],
    ['banana', 'bee'],
    ['carrot', 'chicken'],

]

df = pd.DataFrame(data)
print(df)




    fruit   animal
0   apple   alpaca
1  banana      bee
2  carrot  chicken

        0        1
0   apple   alpaca
1  banana      bee
2  carrot  chicken


In [ ]:
print(df, end="\n\n")
print(df.values, end="\n\n")
print(df.columns, end="\n\n")
print(df.value_counts(), end="\n\n")

        0        1
0   apple   alpaca
1  banana      bee
2  carrot  chicken

[['apple' 'alpaca']
 ['banana' 'bee']
 ['carrot' 'chicken']]

RangeIndex(start=0, stop=2, step=1)

0       1      
apple   alpaca     1
banana  bee        1
carrot  chicken    1
Name: count, dtype: int64



In [ ]:
print(df.info(), end="\n\n")
print(df.head(2), end="\n\n")
print(df.tail(2), end="\n\n")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       3 non-null      object
 1   1       3 non-null      object
dtypes: object(2)
memory usage: 176.0+ bytes
None

        0       1
0   apple  alpaca
1  banana     bee

        0        1
1  banana      bee
2  carrot  chicken



In [ ]:
#행과 열 데이터 보기

print(df, end="\n\n")

print(df.loc[0]) # 인덱스 값 기반의 행 읽기
print(df.loc[1], end="\n\n")

print(df.iloc[0]) # 행 번호 기반의 행 읽기
print(df.iloc[1])

        0        1
0   apple   alpaca
1  banana      bee
2  carrot  chicken

0     apple
1    alpaca
Name: 0, dtype: object
0    banana
1       bee
Name: 1, dtype: object

0     apple
1    alpaca
Name: 0, dtype: object
0    banana
1       bee
Name: 1, dtype: object


In [ ]:
data = {
    'fruit':['apple', 'banana', 'carrot'],
    'animal' : ['alpaca', 'bee', 'chicken']
}
df = pd.DataFrame(data)
print(df, end="\n\n")

print(df.fruit) # df.열이름 : 열 이름 기반의 열 읽기
print()
print(df.animal)
print()

# df[조건식] : 조건을 만족하는 행만 골라서 읽기
# and, or, not 각각 &, |, ~ 으로 표현
print(df[df.fruit == 'apple'])
print()
print(df[(df.animal == 'bee') | (df.animal == 'chicken')])

    fruit   animal
0   apple   alpaca
1  banana      bee
2  carrot  chicken

0     apple
1    banana
2    carrot
Name: fruit, dtype: object

0     alpaca
1        bee
2    chicken
Name: animal, dtype: object

   fruit  animal
0  apple  alpaca

    fruit   animal
1  banana      bee
2  carrot  chicken


In [ ]:
#데이터프레임 이어붙이기
"""
pd.concat() : 행 또는 열 방향으로 데이터 프레임 이어붙이기
df.append() : 행 방향으로 데이터프레임 이어붙이기
=> append() 함수의 경우 라이브러리에서 제외될 예정.(사용 권장x)

"""

'\npd.concat() : 행 또는 열 방향으로 데이터 프레임 이어붙이기\ndf.append() : 행 방향으로 데이터프레임 이어붙이기\n=> append() 함수의 경우 라이브러리에서 제외될 예정.(사용 권장x)\n\n'

In [ ]:
"""
결측값, 이상값, 중복값 등은 데이터 분석에 도움이 되지 않아 분석 전 미리 조치를 취하는 것이 좋다.

결측값: 누락된 데이터를 의미한다.
판다스에서는 결측값을 ‘Not a Number(NaN)' 또는 'None'으로 표기한다.
결측값을 처리할 때는 이를 제거하거나 다른 유효한 값으로 대체하는 방법을 사용한다.

이상값: 다른 대다수의 데이터와 동떨어진 값을 의미한다.
이때는 주로 평균치로 대체 하는 경우가 많다.

중복값: 같은 값이 여러 번 반복되는 경우를 뜻하는데,
이때에도 평균치로 대체하는 방법을 주로 사용한다.


df.isnull() : 각 값의 결측 데이터 여부를 확인하는 함수
df.notnull() : 각 값의 결측 데이터 여부를 확인하는 함수
df.dropna(): 결측 데이터를 제거하는 함수
df.fillna(): 결측 데이터를 다른 값으로 대체하는 함수
df.drop(): 행 또는 열을 제거하는 함수
df.drop_duplicates(): 유일한 1개만 남기고 나머지 중복을 제거하는 함수

"""

print(df)
print()
print(df.isnull())
print()
print(df.notnull())
print()
print(df.dropna())
print()
print(df.sort_values(
    by='fruit',
    ascending=False, #True면 오름차순, False면 내림차순
    inplace=False #복사본 생성 여부, True면 복사본 생성x
))
print()

gb = df.groupby(by='fruit')
print(gb)
print(gb.value_counts())

    fruit   animal
0   apple   alpaca
1  banana      bee
2  carrot  chicken

   fruit  animal
0  False   False
1  False   False
2  False   False

   fruit  animal
0   True    True
1   True    True
2   True    True

    fruit   animal
0   apple   alpaca
1  banana      bee
2  carrot  chicken

    fruit   animal
2  carrot  chicken
1  banana      bee
0   apple   alpaca

fruit   animal 
apple   alpaca     1
banana  bee        1
carrot  chicken    1
Name: count, dtype: int64
